import os
import json
import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from torch.utils.data import DataLoader
from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support,
    confusion_matrix, classification_report
)
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from dataset import MurilSentimentDataset, LABEL_MAP

# Ensure consistent labels matching dataset definitions
class_names = [k for k, v in sorted(LABEL_MAP.items(), key=lambda item: item[1])]

def plot_confusion_matrix(y_true, y_pred, save_path="confusion_matrix.png"):
    cm = confusion_matrix(y_true, y_pred)
    
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
    plt.xlabel('Predicted Sentiment')
    plt.ylabel('True Sentiment')
    plt.title('Confusion Matrix - Final MuRIL Model')
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()
    print(f"✓ Confusion matrix plot saved to {save_path}")

def main():
    model_dir = "saved_models/muril_sentiment/"
    # Check for the test file generated by the MongoDB split script
    test_file = "backend/data/test.json" 
    
    output_metrics = "evaluation_results.json"
    output_report = "classification_report.txt"
    output_cm = "confusion_matrix.png"
    
    # Defined Baseline Metrics
    baseline_acc = 0.68
    baseline_f1 = 0.66
    
    if not os.path.exists(model_dir):
        print(f"Error: Model directory {model_dir} not found.")
        print("Please ensure you have extracted your Colab zip file to 'saved_models/muril_sentiment/'.")
        return
        
    if not os.path.exists(test_file):
        # Fallback to local root test file if backend/data isn't found
        if os.path.exists("test.json"):
            test_file = "test.json"
        else:
            print(f"Error: {test_file} not found.")
            return

    # Automatically detect best available device
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device for inference: {device}")

    print(f"Loading MuRIL tokenizer and model from {model_dir}...")
    tokenizer = AutoTokenizer.from_pretrained(model_dir)
    model = AutoModelForSequenceClassification.from_pretrained(model_dir)
    model.to(device)
    model.eval() # Ensure model is in evaluation mode
    
    print(f"Loading test dataset from {test_file}...")
    test_dataset = MurilSentimentDataset(test_file, tokenizer, max_length=128)
    
    # Use standard PyTorch DataLoader instead of HuggingFace Trainer
    test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)
    
    all_preds = []
    all_labels = []

    print("Running pure PyTorch evaluation loops...")
    # Inference loop without gradient tracking
    with torch.no_grad():
        for batch in test_loader:
            # Move tensors to the correct device
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)
            
            # Forward pass directly on the model
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            
            # Extract highest probability class
            preds = torch.argmax(logits, dim=-1)
            
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            
    # Calculate overarching metrics using standard arrays
    acc = accuracy_score(all_labels, all_preds)
    precision, recall, f1, _ = precision_recall_fscore_support(all_labels, all_preds, average='weighted', zero_division=0)
    
    # Generate and print the text Classification Report
    report_str = classification_report(all_labels, all_preds, target_names=class_names, zero_division=0)
    
    print("\n" + "="*45)
    print("            CLASSIFICATION REPORT            ")
    print("="*45)
    print(report_str)
    
    # Save the text report
    with open(output_report, "w", encoding="utf-8") as f:
        f.write("Classification Report - Final MuRIL Model\n")
        f.write("="*41 + "\n\n")
        f.write(report_str)
    print(f"✓ Classification report saved to {output_report}")
    
    # Generate and save the Confusion Matrix
    plot_confusion_matrix(all_labels, all_preds, save_path=output_cm)
    
    # Save Metrics JSON
    metrics_dict = {
        "accuracy": round(acc, 4),
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1_score": round(f1, 4)
    }
    
    with open(output_metrics, "w", encoding="utf-8") as f:
        json.dump(metrics_dict, f, indent=4)
    print(f"✓ Metrics saved to {output_metrics}")
    
    # Calculate and Print Baseline Comparison
    print("\n" + "="*45)
    print("             BASELINE COMPARISON             ")
    print("="*45)
    
    acc_diff_abs = acc - baseline_acc
    acc_diff_pct = (acc - baseline_acc) / baseline_acc * 100
    
    f1_diff_abs = f1 - baseline_f1
    f1_diff_pct = (f1 - baseline_f1) / baseline_f1 * 100
    
    print(f"Baseline Accuracy:  {baseline_acc*100:.2f}%")
    print(f"MuRIL Accuracy:     {acc*100:.2f}%")
    print(f"  -> Absolute Improvement:   {acc_diff_abs*100:+.2f}%")
    print(f"  -> Percentage Improvement: {acc_diff_pct:+.2f}%\n")
    
    print(f"Baseline Weighted F1: {baseline_f1:.4f}")
    print(f"MuRIL Weighted F1:    {f1:.4f}")
    print(f"  -> Absolute Improvement:   {f1_diff_abs:+.4f}")
    print(f"  -> Percentage Improvement: {f1_diff_pct:+.2f}%")
    print("="*45)

if __name__ == "__main__":
    main()
